### ISSUE TITLE
feature: configurable annotations and labels on objects

### ISSUE THREAD

**Issue by embik** [kcp-dev/kcp-operator#37]
### Feature Description

We create plenty of Kubernetes objects throughout the operator, e.g. `Deployments` and `Services`. We should allow users to configure additional labels and annotations that should be added to those objects, e.g. because you need to pass additional load balancer configuration through an annotation or you want to enable Prometheus scraping on a Deployment.

### Proposed Solution

Add fields to resources that allow to configure flexible label and annotation configuration. I guess it would look something like this:

```yaml
apiVersion: operator.kcp.io/v1alpha1
kind: RootShard
metadata: ...
spec:
    components:
        deployment:
            labels:
                test: test
            annotations:
                test: test
        service:
            labels:
                test: test
            annotations:
                test: test
```

This isn't a final recommendation for the API though, we should look for prior art in other projects and see how these fields are named (`labels` vs `additionalLabels` e.g., should the key really be `components`, etc).

### Want to contribute?

- [ ] I would like to work on this issue.
